name: Test Flask Register and Login

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Define a versão do Python aqui

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -  # Instala Poetry
        export PATH="$HOME/.local/bin:$PATH"  # Adiciona Poetry ao PATH

    - name: Install dependencies with Poetry
      run: |
        poetry install  # Instala as dependências listadas no pyproject.toml

    - name: Run tests with Poetry
      run: |
        poetry run pytest --maxfail=1 --disable-warnings  # Executa os testes com pytest
